blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('posts/', views.PostView.as_view(), name='post_list'),
    path('users/', views.AuthorView.as_view(), name='user_list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', views.PostCreateView.as_view(), name='post_create'),
    path('userpost/<int:pk>/', views.UserPostView.as_view(), name='userposts'),
    path('authorpost/<int:pk>/', views.AuthorPostView.as_view(), name='authorposts'),
    path('posts/update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('help/', views.contact_form, name='help_me')

]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=300)
    text = models.TextField(max_length=3500)
    description = models.TextField(max_length=1000, blank=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    img = models.URLField()
    published = models.BooleanField(default=True)

    def __str__(self):
        return f'{" ".join(self.title.split()[:3])}...'


class Comment(models.Model):
    username = models.CharField(max_length=100)
    text = models.TextField(max_length=1000)
    is_published = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.username}-{" ".join(self.text.split()[:3])}...'

authorization/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('username', 'text', 'post')


class HelpForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render

from django.template.loader import render_to_string
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormMixin

# from practice.settings.components.email import EMAIL_HOST_USER

from .forms import CommentForm, HelpForm
from .models import Comment, Post
from .tasks import need_send_mail

User = get_user_model()


class IndexView(generic.TemplateView):
    template_name = "base_generic.html"


class PostView(generic.ListView):
    model = Post
    queryset = Post.objects.select_related("author"). \
        filter(published=True).annotate(num=Count('comment'))
    paginate_by = 20


class AuthorView(generic.ListView):
    model = User
    template_name = 'blog/user_list.html'
    queryset = User.objects.annotate(num=Count('post'))
    paginate_by = 20


class PostDetailView(FormMixin, generic.DetailView):
    model = Post
    form_class = CommentForm

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        q = Comment.objects.filter(post_id=self.object.pk).filter(is_published=True)
        contex = super(PostDetailView, self).get_context_data()
        contex['com'] = q
        contex['form'] = CommentForm(initial={'post': self.object})
        return contex

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save()
        post = self.get_object()
        email = Post.objects.get(id=self.object.id).author.email
        # -----------just for me-------------------------------
        # send_mail('New comment',
        #           f"New comment on post: {post}. "
        #           f"Was written by {comment.username}. "
        #           f"URL:{reverse('blog:post_detail', kwargs={'pk': self.object.id})}",
        #           EMAIL_HOST_USER, ['olyaluchko@gmail.com', ], fail_silently=True)
        # -----------------------------------------------------
        send_mail('New comment',
                  f"New comment on post: {post}. "
                  f"Was written by {comment.username}. "
                  f"URL:{reverse('blog:post_detail', kwargs={'pk': self.object.id})}",
                  'admin@mail.com', [email, ], fail_silently=True)

        Comment(username=comment.username,
                text=comment.text, is_published=False,
                post_id=post)
        return super(PostDetailView, self).form_valid(form)


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    fields = ['title', 'text', 'img', 'description', 'author', 'published']

    def get_success_url(self):
        send_mail('New post', f"New post: {self.object.title}({self.object.pk})",
                  "admin@mail.com", ['admin@mail.com', ])
        return reverse('blog:post_detail', kwargs={'pk': self.object.pk})


class PostUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Post
    fields = ['title', 'text', 'img', 'description', 'published']
    template_name = 'blog/post_update_form.html'
    success_message = "Post updated"

    def get_context_data(self, *args, **kwargs):
        queryset = Post.objects.get(id=self.kwargs['pk'])
        contex = super().get_context_data()
        contex['post_list'] = queryset
        return contex


class UserPostView(generic.ListView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        queryset = Post.objects.filter(author_id=self.kwargs['pk']). \
            annotate(num=Count('comment')).order_by('pk')
        contex = super().get_context_data()
        contex['post_list'] = queryset
        contex['ifuser'] = True
        return contex


class AuthorPostView(generic.ListView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        queryset = Post.objects.filter(author_id=self.kwargs['pk']). \
            annotate(num=Count('comment')).order_by('pk')
        contex = super().get_context_data()
        contex['post_list'] = queryset
        return contex


def contact_form_save(request, form, template_name):
    data = dict()
    if request.method == "POST":
        if form.is_valid():
            data['form_is_valid'] = True
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            need_send_mail.apply_async((subject, from_email, message))
            messages.success(request, 'Email was send successfully')
            context = {'form': form}
            data['html_form'] = render_to_string(template_name, context, request=request)
            return JsonResponse(data)
        else:
            data['form_is_valid'] = False
            messages.error(request, 'Email was not send')
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def contact_form(request):
    if request.method == "POST":
        form = HelpForm(request.POST)
    else:
        form = HelpForm()
    return contact_form_save(request, form, 'blog/help.html')

templates/blog/help.html
{#{% extends "mini_base.html" %}#}
{##}
{#{% block title %}<h5 class="card-title text-center mb-5 fw-light fs-5 font">Smth Wrong? Contact Us!</h5>{% endblock %}#}
{#{% block content %}#}
{% load static %}

<link href="{% static 'css/modal_style.css' %}" rel="stylesheet" type="text/css">
<form method="POST" action="{% url 'blog:help_me' %}" class="js-blog-contact">
    {% csrf_token %}
    <div class="modal-header">
        <h3 class="modal-title modtit">Contact Us</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% if messages %}
     {% for message in messages %}
         <div class="text-center alert-{{ message.tags }}">{{ message|safe }}
         </div>
     {% endfor %}
 {% endif %}
    <div class="modal-body">

        <div class="form-floating mb-3 mar">

            <input type="text"
                   class="form-control hei" name=subject
                   id="id_subject"
                   placeholder="Subject">
            <div class="small" style="color: red"> {% if form.subject.errors %}
                {{ form.subject.errors }}
            {% endif %}</div>

        </div>
        <div class="form-floating mb-3 mar">

            <input type="email"
                   class="form-control hei" name=from_email
                   id="id_email"
                   placeholder="E-mail">
            <div class="small" style="color: red"> {% if form.from_email.errors %}
                {{ form.from_email.errors }}
            {% endif %}</div>
        </div>
        <div class="form-floating mb-3 mar">
            <textarea
                    type="text" class="form-control hei"
                    name="message" id="id_message"
                    placeholder="Message"></textarea>
            <div class="small" style="color: red"> {% if form.message.errors %}
                {{ form.message.errors }}
            {% endif %}</div>
        </div>


        <div class="d-grid mb-2">
            <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase font "
                    type="submit">
                Send Mail
            </button>
        </div>

    </div>
</form>

{#{% endblock %}#}

templates/blog/post_detail.html
{% extends "base_generic.html" %}

{% block title %}{{ object.title }}{% endblock %}
{% block content %}
        {% load cache %}
    {% cache 30 object.author object.img object.description object.text%}
    <p>Author - {{ object.author }}</p>
    <div><img style="margin-left: 5%; margin-bottom: 10pt" src="{{ object.img }}" alt="" ></div>

    Description:
    <div>{{ object.description }}</div>
    <hr>
    <div>{{ object.text }}</div>
    <hr style="margin-left: 10pt; margin-top: 10%">
    {% endcache %}
    <div class="container">

            <div class="col-sm-8">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                            {{ field.errors }}
                    {% endfor %}
                    <h3 class="text-info" style="font-family: 'Montserrat', 'PT Sans', sans-serif; ">
                        New Comment</h3>

                    <fieldset>

                        <div class="row">
                            <div class="col-sm-3 col-lg-2 hidden-xs">
                                <img class="rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar3.png"
                                     width="60" alt="">
                            </div>
                            <div class="form-group col-xs-12 col-sm-9 col-lg-10">

                                <input class="form-control"
                                       id="id_username" name="username" required
                                       type="text" placeholder="Username"/>

                                <textarea class="form-control" id="id_text" maxlength=1000
                                           rows=5  name="text" placeholder="Your message"
                                                                       required=""></textarea>

                                <input class="form-control"
                                       id="id_post" type="hidden" name="post" placeholder="Username" value="{{ object.pk }}"/>
                            </div>

                        </div>
                    </fieldset>
                    <button type="submit" class="btn btn-info pull-right" style="margin-left: 85%">Submit
                                                   </button>
                </form>
            </div>

           <div style="margin-left: 10pt"> <hr>
               <h3 class="text-info" style="font-family: 'Montserrat', 'PT Sans', sans-serif; ">Comments</h3>

            {% for c in com %}
                <hr>
                <div class="media ">
                    <img class="media-object rounded-circle" width="60"
                         src="https://bootdey.com/img/Content/avatar/avatar2.png"
                         alt="">
                    <div class="media-body " style="margin-left: 10pt">
                        <h4 class="media-heading"
                            style="font-family: 'Montserrat', 'PT Sans', sans-serif; ">{{ c.username }}</h4>
                        <p style="font-family: 'Montserrat', 'PT Sans', sans-serif; ">{{ c.text }}</p>

                    </div>
                </div>
            {% endfor %}
    </div>
        </div>

{% endblock %}

templates/blog/post_form.html
{% extends "base_generic.html" %}
{% block title %}List of Posts{% endblock %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div style="font-size: small; color: red">
            {% for field in form.visible_fields %}
                {{ field.errors }}
            {% endfor %}</div>

        <div class="form-floating mb-3 mar">
            <label for="id_title" class="lab"> Title:</label>
            <input type="text" required
                   class="form-control hei" name=title
                   id="id_title"
                   placeholder="">

        </div>

        <div class="form-floating mb-3 mar">

            <label for="id_description" class="lab"> Description:</label>
            <input type="text"
                   class="form-control hei" name=description
                   id="id_description"
                   placeholder="">

        </div>


        <div class="form-floating mb-3 mar">

            <label for="id_img" class="lab"> Image URL:</label>
            <input type="url" required
                   class="form-control hei" name=img
                   id="id_img"
                   placeholder="">

        </div>


        <div class="form-floating mb-3 mar">

            <label for="id_text" class="lab"> Post:</label>
            <div>
                <textarea name="text" required id="id_text" maxlength="3500" cols="50" rows="20"></textarea></div>


        </div>

        <div class="form-floating mb-3 mar">
            <label for="id_author">Author:</label>
            <input type="text"
                   class="form-control hei" name=author
                   id="id_author"
                   placeholder="" value="{{ user.id }}" readonly>
        </div>

 <div class="form-floating mb-3 mar" >

            <label for="id_published">Choose status:</label>
            <div><p class="small">Publicate:<input style="width: 10pt" type="radio"
                   class="form-control hei" name=published
                   id="id_published" value="True"
            ></p>
            <p class="small">Don`t:<input style="width: 10pt" type="radio"
                   class="form-control hei" name=published
                   id="id_published" value="False"
            ></p>
            </div>
        </div>

        <div class="d-grid mb-2">
            <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase font" type="submit">
                Create post
            </button>
        </div>
    </form>


{% endblock %}

templates/blog/post_list.html
{% extends "base_generic.html" %}

{% block title %}List of Posts{% endblock %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Comments</th>
            {% if request.user.username == user.username %}
                {% if  ifuser %}
                    <th scope="col">Edit</th>
                {% endif %}{% endif %}
        </tr>
        </thead>
        <tbody>
        {% if post_list %}
            {% for post in post_list %}

                <tr>
                    <th scope="row"><a href="{% url 'blog:post_detail' pk=post.pk %}">
                        {{ post.title }}</a></th>
                    <td>by {{ post.author.username }}</td>
                    <td>{{ post.num }}</td>
                    {% if request.user.username == user.username %}
                        {% if  ifuser %}
                            <td>
                                <div class="d-grid mb-2 ">
                                    <button class="btn  btn-warning "
                                            style="font-family:
                                            'Montserrat', 'PT Sans', sans-serif;" type="submit">
                                        <a style="color: white" href="{% url 'blog:post_update' pk=post.pk %}">Update</a>
                                    </button>
                                </div>
                            </td>{% endif %}{% endif %}
                </tr>

            {% endfor %}
        {% else %}

            <td class="table-warning">There are no posts</td>
            <td class="table-warning"></td>
            <td class="table-warning"></td>
        {% endif %}
        </tbody>
    </table>

{% endblock %}

templates/blog/post_update_form.html
{% extends "base_generic.html" %}
{% block title %}List of Posts{% endblock %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
 <div style="font-size: small; color: red">
 {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
 {% endif %}
     {% for field in form.visible_fields %}
                            {{ field.errors }}
                        {% endfor %}</div>

        <div class="form-floating mb-3 mar">

            <label for="id_title" class="lab"> Title:</label>
            <input type="text" required
                   class="form-control hei" name=title
                   id="id_title"
                   placeholder="" value="{{ post_list.title }}">

        </div>

        <div class="form-floating mb-3 mar">

            <label for="id_description" class="lab"> Description:</label>
            <input type="text"
                   class="form-control hei" name=description
                   id="id_description"
                   placeholder="" value="{{ post_list.description }}">

        </div>


        <div class="form-floating mb-3 mar">

            <label for="id_img" class="lab"> Image URL:</label>
            <input type="url" required
                   class="form-control hei" name=img
                   id="id_img"
                   placeholder="" value="{{ post_list.img }}">

        </div>


        <div class="form-floating mb-3 mar">

            <label for="id_text" class="lab"> Post:</label>
            <div>
            <textarea wrap="soft"  name="text" required id="id_text"
                      maxlength="3500" cols="50" rows="20" >{{ post_list.text }}</textarea></div>
        </div>
        <div class="form-floating mb-3 mar" >

            <label for="id_published">Current status: {{ post_list.published }}, publish?</label>
            <div><p class="small">True:<input style="width: 10pt" type="radio"
                   class="form-control hei" name=published
                   id="id_published" value="True"
            ></p>
            <p class="small">False:<input style="width: 10pt" type="radio"
                   class="form-control hei" name=published
                   id="id_published" value="False"
            ></p>
            </div>
        </div>
        <div class="d-grid mb-2">
            <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase font" type="submit">
                Update post
            </button>
        </div>
    </form>


{% endblock %}

templates/blog/user_list.html
{% extends "base_generic.html" %}

{% block title %}List of Authors{% endblock %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Username</th>
            <th scope="col">Fist Name</th>
            <th scope="col">Last Name</th>

            <th scope="col">Number of posts</th>

        </tr>
        </thead>
        <tbody>
        {% if user_list %}
            {% for user in user_list %}

                <tr>
                <th scope="row"><a href="{% url 'profile' pk=user.pk %}">{{ user.username }}</a></th>
                {% if user.first_name %}
                    <td>{{ user.first_name }}</td>
                {% else %}
                    <td>—</td>
                {% endif %}
                {% if user.last_name %}
                    <td>{{ user.last_name }}</td>
                {% else %}
                    <td>—</td>
                {% endif %}

                <td><a href="{% url 'blog:authorposts' pk=user.pk %}">{{ user.num }}</a></td>

            {% endfor %}
        {% else %}
            <td class="table-warning">There are no authors</td>
            <td class="table-warning"></td>
            <td class="table-warning"></td>
            <td class="table-warning"></td>
        {% endif %}
        </tbody>
    </table>


{% endblock %}